ARMAROW_DIR=../../../

CXXFLAGS+=-Wall -Os

PLATFORM=${ARMAROW_DIR}/platform/deRCB128RFA1

BIN=./bin
SRC=./src
BUILD=./build
INC=./include

.PHONY: default

default: help

include ${ARMAROW_DIR}/make/example.mk
