################################################################################
##
## Copyright (c) 2010 Michael Schulze <mschulze@ivs.cs.uni-magdeburg.de>
ARMAROWDIR=../../../

CXXFLAGS+=-Wall -Os

PLATFORM=deRCB128RFA1_newDriver

BIN=./bin
SRC=.
BUILD=./build
INCLUDE=.

.PHONY: default

default: help

include ${ARMAROWDIR}/make/example.mk
